// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adverse_event.proto

package datacenter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RepSearch struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepSearch) Reset()         { *m = RepSearch{} }
func (m *RepSearch) String() string { return proto.CompactTextString(m) }
func (*RepSearch) ProtoMessage()    {}
func (*RepSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_54cc3fec8bb419ba, []int{0}
}

func (m *RepSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepSearch.Unmarshal(m, b)
}
func (m *RepSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepSearch.Marshal(b, m, deterministic)
}
func (m *RepSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepSearch.Merge(m, src)
}
func (m *RepSearch) XXX_Size() int {
	return xxx_messageInfo_RepSearch.Size(m)
}
func (m *RepSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RepSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RepSearch proto.InternalMessageInfo

func (m *RepSearch) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type ResSearch struct {
	Code                 int64                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	DataInfo             []*AdverseEventSearchModel `protobuf:"bytes,3,rep,name=data_info,json=dataInfo,proto3" json:"data_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ResSearch) Reset()         { *m = ResSearch{} }
func (m *ResSearch) String() string { return proto.CompactTextString(m) }
func (*ResSearch) ProtoMessage()    {}
func (*ResSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_54cc3fec8bb419ba, []int{1}
}

func (m *ResSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResSearch.Unmarshal(m, b)
}
func (m *ResSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResSearch.Marshal(b, m, deterministic)
}
func (m *ResSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResSearch.Merge(m, src)
}
func (m *ResSearch) XXX_Size() int {
	return xxx_messageInfo_ResSearch.Size(m)
}
func (m *ResSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ResSearch.DiscardUnknown(m)
}

var xxx_messageInfo_ResSearch proto.InternalMessageInfo

func (m *ResSearch) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResSearch) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResSearch) GetDataInfo() []*AdverseEventSearchModel {
	if m != nil {
		return m.DataInfo
	}
	return nil
}

type RepAdverseEventView struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepAdverseEventView) Reset()         { *m = RepAdverseEventView{} }
func (m *RepAdverseEventView) String() string { return proto.CompactTextString(m) }
func (*RepAdverseEventView) ProtoMessage()    {}
func (*RepAdverseEventView) Descriptor() ([]byte, []int) {
	return fileDescriptor_54cc3fec8bb419ba, []int{2}
}

func (m *RepAdverseEventView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepAdverseEventView.Unmarshal(m, b)
}
func (m *RepAdverseEventView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepAdverseEventView.Marshal(b, m, deterministic)
}
func (m *RepAdverseEventView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepAdverseEventView.Merge(m, src)
}
func (m *RepAdverseEventView) XXX_Size() int {
	return xxx_messageInfo_RepAdverseEventView.Size(m)
}
func (m *RepAdverseEventView) XXX_DiscardUnknown() {
	xxx_messageInfo_RepAdverseEventView.DiscardUnknown(m)
}

var xxx_messageInfo_RepAdverseEventView proto.InternalMessageInfo

func (m *RepAdverseEventView) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type AdverseEventSearchModel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Integration          string   `protobuf:"bytes,2,opt,name=integration,proto3" json:"integration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdverseEventSearchModel) Reset()         { *m = AdverseEventSearchModel{} }
func (m *AdverseEventSearchModel) String() string { return proto.CompactTextString(m) }
func (*AdverseEventSearchModel) ProtoMessage()    {}
func (*AdverseEventSearchModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_54cc3fec8bb419ba, []int{3}
}

func (m *AdverseEventSearchModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdverseEventSearchModel.Unmarshal(m, b)
}
func (m *AdverseEventSearchModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdverseEventSearchModel.Marshal(b, m, deterministic)
}
func (m *AdverseEventSearchModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdverseEventSearchModel.Merge(m, src)
}
func (m *AdverseEventSearchModel) XXX_Size() int {
	return xxx_messageInfo_AdverseEventSearchModel.Size(m)
}
func (m *AdverseEventSearchModel) XXX_DiscardUnknown() {
	xxx_messageInfo_AdverseEventSearchModel.DiscardUnknown(m)
}

var xxx_messageInfo_AdverseEventSearchModel proto.InternalMessageInfo

func (m *AdverseEventSearchModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdverseEventSearchModel) GetIntegration() string {
	if m != nil {
		return m.Integration
	}
	return ""
}

type AdverseEventModel struct {
	Id                    int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainType            string   `protobuf:"bytes,2,opt,name=domain_type,json=domainType,proto3" json:"domain_type,omitempty"`
	DomainId              int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	DomainName            string   `protobuf:"bytes,4,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	DomainAddresss        string   `protobuf:"bytes,5,opt,name=domain_addresss,json=domainAddresss,proto3" json:"domain_addresss,omitempty"`
	DomainCreatetime      string   `protobuf:"bytes,6,opt,name=domain_createtime,json=domainCreatetime,proto3" json:"domain_createtime,omitempty"`
	PatientSex            string   `protobuf:"bytes,7,opt,name=patient_sex,json=patientSex,proto3" json:"patient_sex,omitempty"`
	PatientName           string   `protobuf:"bytes,8,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	PatientAge            string   `protobuf:"bytes,9,opt,name=patient_age,json=patientAge,proto3" json:"patient_age,omitempty"`
	PatientType           string   `protobuf:"bytes,10,opt,name=patient_type,json=patientType,proto3" json:"patient_type,omitempty"`
	PatientState          string   `protobuf:"bytes,11,opt,name=patient_state,json=patientState,proto3" json:"patient_state,omitempty"`
	EventPlaceType        string   `protobuf:"bytes,12,opt,name=event_place_type,json=eventPlaceType,proto3" json:"event_place_type,omitempty"`
	EventPlace            string   `protobuf:"bytes,13,opt,name=event_place,json=eventPlace,proto3" json:"event_place,omitempty"`
	EventTime             string   `protobuf:"bytes,14,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	EventScene            string   `protobuf:"bytes,15,opt,name=event_scene,json=eventScene,proto3" json:"event_scene,omitempty"`
	EventType             string   `protobuf:"bytes,16,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventMemo             string   `protobuf:"bytes,17,opt,name=event_memo,json=eventMemo,proto3" json:"event_memo,omitempty"`
	Symptom               string   `protobuf:"bytes,18,opt,name=symptom,proto3" json:"symptom,omitempty"`
	Dispose               string   `protobuf:"bytes,19,opt,name=dispose,proto3" json:"dispose,omitempty"`
	DisposeWorkerType     string   `protobuf:"bytes,20,opt,name=dispose_worker_type,json=disposeWorkerType,proto3" json:"dispose_worker_type,omitempty"`
	DisposeWorkerTitle    string   `protobuf:"bytes,21,opt,name=dispose_worker_title,json=disposeWorkerTitle,proto3" json:"dispose_worker_title,omitempty"`
	DisposeWorkerAge      string   `protobuf:"bytes,22,opt,name=dispose_worker_age,json=disposeWorkerAge,proto3" json:"dispose_worker_age,omitempty"`
	DisposeWorkerName     string   `protobuf:"bytes,23,opt,name=dispose_worker_name,json=disposeWorkerName,proto3" json:"dispose_worker_name,omitempty"`
	DisposeWorkerSex      string   `protobuf:"bytes,24,opt,name=dispose_worker_sex,json=disposeWorkerSex,proto3" json:"dispose_worker_sex,omitempty"`
	EventLv               string   `protobuf:"bytes,25,opt,name=event_lv,json=eventLv,proto3" json:"event_lv,omitempty"`
	EventResult           string   `protobuf:"bytes,26,opt,name=event_result,json=eventResult,proto3" json:"event_result,omitempty"`
	EventReason           string   `protobuf:"bytes,27,opt,name=event_reason,json=eventReason,proto3" json:"event_reason,omitempty"`
	EventReasonMemo       string   `protobuf:"bytes,28,opt,name=event_reason_memo,json=eventReasonMemo,proto3" json:"event_reason_memo,omitempty"`
	FollowUpl             string   `protobuf:"bytes,29,opt,name=follow_upl,json=followUpl,proto3" json:"follow_upl,omitempty"`
	QcUserName            string   `protobuf:"bytes,30,opt,name=qc_user_name,json=qcUserName,proto3" json:"qc_user_name,omitempty"`
	QcUserAge             string   `protobuf:"bytes,31,opt,name=qc_user_age,json=qcUserAge,proto3" json:"qc_user_age,omitempty"`
	QcUserSex             string   `protobuf:"bytes,32,opt,name=qc_user_sex,json=qcUserSex,proto3" json:"qc_user_sex,omitempty"`
	QcUserType            string   `protobuf:"bytes,33,opt,name=qc_user_type,json=qcUserType,proto3" json:"qc_user_type,omitempty"`
	QcUserTitle           string   `protobuf:"bytes,34,opt,name=qc_user_title,json=qcUserTitle,proto3" json:"qc_user_title,omitempty"`
	Preventive            string   `protobuf:"bytes,35,opt,name=preventive,proto3" json:"preventive,omitempty"`
	PreventiveManager     string   `protobuf:"bytes,36,opt,name=preventive_manager,json=preventiveManager,proto3" json:"preventive_manager,omitempty"`
	AccidentLiability     string   `protobuf:"bytes,37,opt,name=accident_liability,json=accidentLiability,proto3" json:"accident_liability,omitempty"`
	PreventiveManagePost  string   `protobuf:"bytes,38,opt,name=preventive_manage_post,json=preventiveManagePost,proto3" json:"preventive_manage_post,omitempty"`
	PreventiveManageAge   string   `protobuf:"bytes,39,opt,name=preventive_manage_age,json=preventiveManageAge,proto3" json:"preventive_manage_age,omitempty"`
	PreventiveManageSex   string   `protobuf:"bytes,40,opt,name=preventive_manage_sex,json=preventiveManageSex,proto3" json:"preventive_manage_sex,omitempty"`
	PreventiveManageTitle string   `protobuf:"bytes,41,opt,name=preventive_manage_title,json=preventiveManageTitle,proto3" json:"preventive_manage_title,omitempty"`
	PatientStateMemo      string   `protobuf:"bytes,42,opt,name=patient_state_memo,json=patientStateMemo,proto3" json:"patient_state_memo,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *AdverseEventModel) Reset()         { *m = AdverseEventModel{} }
func (m *AdverseEventModel) String() string { return proto.CompactTextString(m) }
func (*AdverseEventModel) ProtoMessage()    {}
func (*AdverseEventModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_54cc3fec8bb419ba, []int{4}
}

func (m *AdverseEventModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdverseEventModel.Unmarshal(m, b)
}
func (m *AdverseEventModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdverseEventModel.Marshal(b, m, deterministic)
}
func (m *AdverseEventModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdverseEventModel.Merge(m, src)
}
func (m *AdverseEventModel) XXX_Size() int {
	return xxx_messageInfo_AdverseEventModel.Size(m)
}
func (m *AdverseEventModel) XXX_DiscardUnknown() {
	xxx_messageInfo_AdverseEventModel.DiscardUnknown(m)
}

var xxx_messageInfo_AdverseEventModel proto.InternalMessageInfo

func (m *AdverseEventModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdverseEventModel) GetDomainType() string {
	if m != nil {
		return m.DomainType
	}
	return ""
}

func (m *AdverseEventModel) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *AdverseEventModel) GetDomainName() string {
	if m != nil {
		return m.DomainName
	}
	return ""
}

func (m *AdverseEventModel) GetDomainAddresss() string {
	if m != nil {
		return m.DomainAddresss
	}
	return ""
}

func (m *AdverseEventModel) GetDomainCreatetime() string {
	if m != nil {
		return m.DomainCreatetime
	}
	return ""
}

func (m *AdverseEventModel) GetPatientSex() string {
	if m != nil {
		return m.PatientSex
	}
	return ""
}

func (m *AdverseEventModel) GetPatientName() string {
	if m != nil {
		return m.PatientName
	}
	return ""
}

func (m *AdverseEventModel) GetPatientAge() string {
	if m != nil {
		return m.PatientAge
	}
	return ""
}

func (m *AdverseEventModel) GetPatientType() string {
	if m != nil {
		return m.PatientType
	}
	return ""
}

func (m *AdverseEventModel) GetPatientState() string {
	if m != nil {
		return m.PatientState
	}
	return ""
}

func (m *AdverseEventModel) GetEventPlaceType() string {
	if m != nil {
		return m.EventPlaceType
	}
	return ""
}

func (m *AdverseEventModel) GetEventPlace() string {
	if m != nil {
		return m.EventPlace
	}
	return ""
}

func (m *AdverseEventModel) GetEventTime() string {
	if m != nil {
		return m.EventTime
	}
	return ""
}

func (m *AdverseEventModel) GetEventScene() string {
	if m != nil {
		return m.EventScene
	}
	return ""
}

func (m *AdverseEventModel) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *AdverseEventModel) GetEventMemo() string {
	if m != nil {
		return m.EventMemo
	}
	return ""
}

func (m *AdverseEventModel) GetSymptom() string {
	if m != nil {
		return m.Symptom
	}
	return ""
}

func (m *AdverseEventModel) GetDispose() string {
	if m != nil {
		return m.Dispose
	}
	return ""
}

func (m *AdverseEventModel) GetDisposeWorkerType() string {
	if m != nil {
		return m.DisposeWorkerType
	}
	return ""
}

func (m *AdverseEventModel) GetDisposeWorkerTitle() string {
	if m != nil {
		return m.DisposeWorkerTitle
	}
	return ""
}

func (m *AdverseEventModel) GetDisposeWorkerAge() string {
	if m != nil {
		return m.DisposeWorkerAge
	}
	return ""
}

func (m *AdverseEventModel) GetDisposeWorkerName() string {
	if m != nil {
		return m.DisposeWorkerName
	}
	return ""
}

func (m *AdverseEventModel) GetDisposeWorkerSex() string {
	if m != nil {
		return m.DisposeWorkerSex
	}
	return ""
}

func (m *AdverseEventModel) GetEventLv() string {
	if m != nil {
		return m.EventLv
	}
	return ""
}

func (m *AdverseEventModel) GetEventResult() string {
	if m != nil {
		return m.EventResult
	}
	return ""
}

func (m *AdverseEventModel) GetEventReason() string {
	if m != nil {
		return m.EventReason
	}
	return ""
}

func (m *AdverseEventModel) GetEventReasonMemo() string {
	if m != nil {
		return m.EventReasonMemo
	}
	return ""
}

func (m *AdverseEventModel) GetFollowUpl() string {
	if m != nil {
		return m.FollowUpl
	}
	return ""
}

func (m *AdverseEventModel) GetQcUserName() string {
	if m != nil {
		return m.QcUserName
	}
	return ""
}

func (m *AdverseEventModel) GetQcUserAge() string {
	if m != nil {
		return m.QcUserAge
	}
	return ""
}

func (m *AdverseEventModel) GetQcUserSex() string {
	if m != nil {
		return m.QcUserSex
	}
	return ""
}

func (m *AdverseEventModel) GetQcUserType() string {
	if m != nil {
		return m.QcUserType
	}
	return ""
}

func (m *AdverseEventModel) GetQcUserTitle() string {
	if m != nil {
		return m.QcUserTitle
	}
	return ""
}

func (m *AdverseEventModel) GetPreventive() string {
	if m != nil {
		return m.Preventive
	}
	return ""
}

func (m *AdverseEventModel) GetPreventiveManager() string {
	if m != nil {
		return m.PreventiveManager
	}
	return ""
}

func (m *AdverseEventModel) GetAccidentLiability() string {
	if m != nil {
		return m.AccidentLiability
	}
	return ""
}

func (m *AdverseEventModel) GetPreventiveManagePost() string {
	if m != nil {
		return m.PreventiveManagePost
	}
	return ""
}

func (m *AdverseEventModel) GetPreventiveManageAge() string {
	if m != nil {
		return m.PreventiveManageAge
	}
	return ""
}

func (m *AdverseEventModel) GetPreventiveManageSex() string {
	if m != nil {
		return m.PreventiveManageSex
	}
	return ""
}

func (m *AdverseEventModel) GetPreventiveManageTitle() string {
	if m != nil {
		return m.PreventiveManageTitle
	}
	return ""
}

func (m *AdverseEventModel) GetPatientStateMemo() string {
	if m != nil {
		return m.PatientStateMemo
	}
	return ""
}

type ResAdverseEvent struct {
	Code                 int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	DataInfo             []*AdverseEventModel `protobuf:"bytes,3,rep,name=data_info,json=dataInfo,proto3" json:"data_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResAdverseEvent) Reset()         { *m = ResAdverseEvent{} }
func (m *ResAdverseEvent) String() string { return proto.CompactTextString(m) }
func (*ResAdverseEvent) ProtoMessage()    {}
func (*ResAdverseEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_54cc3fec8bb419ba, []int{5}
}

func (m *ResAdverseEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResAdverseEvent.Unmarshal(m, b)
}
func (m *ResAdverseEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResAdverseEvent.Marshal(b, m, deterministic)
}
func (m *ResAdverseEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResAdverseEvent.Merge(m, src)
}
func (m *ResAdverseEvent) XXX_Size() int {
	return xxx_messageInfo_ResAdverseEvent.Size(m)
}
func (m *ResAdverseEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ResAdverseEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ResAdverseEvent proto.InternalMessageInfo

func (m *ResAdverseEvent) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResAdverseEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResAdverseEvent) GetDataInfo() []*AdverseEventModel {
	if m != nil {
		return m.DataInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*RepSearch)(nil), "datacenter.RepSearch")
	proto.RegisterType((*ResSearch)(nil), "datacenter.ResSearch")
	proto.RegisterType((*RepAdverseEventView)(nil), "datacenter.RepAdverseEventView")
	proto.RegisterType((*AdverseEventSearchModel)(nil), "datacenter.AdverseEventSearchModel")
	proto.RegisterType((*AdverseEventModel)(nil), "datacenter.AdverseEventModel")
	proto.RegisterType((*ResAdverseEvent)(nil), "datacenter.ResAdverseEvent")
}

func init() { proto.RegisterFile("adverse_event.proto", fileDescriptor_54cc3fec8bb419ba) }

var fileDescriptor_54cc3fec8bb419ba = []byte{
	// 960 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x72, 0xdb, 0x36,
	0x13, 0x9d, 0x48, 0x8e, 0x63, 0xad, 0xe4, 0x1f, 0x41, 0x76, 0x8c, 0xf8, 0x57, 0x96, 0x93, 0x2f,
	0x4e, 0xbe, 0xc6, 0xee, 0xb8, 0x9d, 0x5e, 0xf4, 0xaa, 0x9e, 0xba, 0x17, 0x9a, 0xc6, 0x9d, 0x8c,
	0x94, 0xb4, 0x37, 0x9d, 0xe1, 0x20, 0xe4, 0x5a, 0xe6, 0x84, 0x24, 0x18, 0x02, 0x96, 0xa3, 0x76,
	0x7a, 0xd3, 0x57, 0xe8, 0x3b, 0xb5, 0x0f, 0xd0, 0x57, 0xe8, 0x83, 0x74, 0xb0, 0x80, 0x64, 0x88,
	0x92, 0x3d, 0xbd, 0x23, 0x76, 0xcf, 0x39, 0x58, 0x9e, 0x5d, 0x12, 0x80, 0x96, 0x88, 0x86, 0x58,
	0x28, 0x0c, 0x70, 0x88, 0x99, 0x3e, 0xce, 0x0b, 0xa9, 0x25, 0x83, 0x48, 0x68, 0x11, 0x62, 0xa6,
	0xb1, 0xd8, 0xda, 0x19, 0x48, 0x39, 0x48, 0xf0, 0x44, 0xe4, 0xf1, 0x89, 0xc8, 0x32, 0xa9, 0x85,
	0x8e, 0x65, 0xa6, 0x2c, 0xb2, 0xf3, 0x0c, 0x6a, 0x3d, 0xcc, 0xfb, 0x28, 0x8a, 0xf0, 0x8a, 0x71,
	0x78, 0xf4, 0x01, 0x47, 0x37, 0xb2, 0x88, 0xf8, 0x83, 0xf6, 0x83, 0xa3, 0x5a, 0x6f, 0xbc, 0xec,
	0x28, 0x03, 0x53, 0x0e, 0xc6, 0x60, 0x21, 0x94, 0x11, 0x12, 0xa6, 0xda, 0xa3, 0x67, 0xb6, 0x06,
	0xd5, 0x54, 0x0d, 0x78, 0x85, 0x68, 0xe6, 0x91, 0x7d, 0x03, 0x35, 0x53, 0x45, 0x10, 0x67, 0x97,
	0x92, 0x57, 0xdb, 0xd5, 0xa3, 0xfa, 0xe9, 0xe1, 0xf1, 0x6d, 0x5d, 0xc7, 0x67, 0xb6, 0xee, 0xef,
	0x4c, 0xd9, 0x56, 0xf8, 0x42, 0x46, 0x98, 0xf4, 0x96, 0x0c, 0xa6, 0x9b, 0x5d, 0x9a, 0xda, 0x5a,
	0x3d, 0xcc, 0x7d, 0xdc, 0x8f, 0x31, 0xde, 0xb0, 0x15, 0xa8, 0x74, 0xcf, 0xdd, 0xe6, 0x95, 0xee,
	0x79, 0xe7, 0x7b, 0xd8, 0xbc, 0x43, 0xcb, 0x40, 0xe3, 0x68, 0x0c, 0x8d, 0x23, 0xd6, 0x86, 0x7a,
	0x9c, 0x69, 0x1c, 0x14, 0xe4, 0x81, 0xab, 0xd6, 0x0f, 0x75, 0xfe, 0x6c, 0x40, 0xd3, 0x57, 0x9b,
	0xaf, 0xb3, 0x0f, 0xf5, 0x48, 0xa6, 0x22, 0xce, 0x02, 0x3d, 0xca, 0xd1, 0xe9, 0x80, 0x0d, 0xbd,
	0x1d, 0xe5, 0xc8, 0xb6, 0xa1, 0xe6, 0x00, 0x71, 0xc4, 0xab, 0xc4, 0x5b, 0xb2, 0x81, 0xae, 0xcf,
	0xce, 0x44, 0x8a, 0x7c, 0xc1, 0x67, 0xff, 0x20, 0x52, 0x64, 0xcf, 0x61, 0xd5, 0x01, 0x44, 0x14,
	0x15, 0xa8, 0x94, 0xe2, 0x0f, 0x09, 0xb4, 0x62, 0xc3, 0x67, 0x2e, 0xca, 0xfe, 0x0f, 0x4d, 0x07,
	0x0c, 0x0b, 0x14, 0x1a, 0x75, 0x9c, 0x22, 0x5f, 0x24, 0xe8, 0x9a, 0x4d, 0x7c, 0x3b, 0x89, 0x9b,
	0x6d, 0x73, 0xa1, 0x63, 0xcc, 0x74, 0xa0, 0xf0, 0x13, 0x7f, 0x64, 0xb7, 0x75, 0xa1, 0x3e, 0x7e,
	0x62, 0x07, 0xd0, 0x18, 0x03, 0xa8, 0xb0, 0x25, 0x6b, 0x8f, 0x8b, 0x51, 0x65, 0x9e, 0x86, 0x18,
	0x20, 0xaf, 0x4d, 0x69, 0x9c, 0x0d, 0xd0, 0xd7, 0x20, 0x6b, 0x60, 0x4a, 0x83, 0xbc, 0x39, 0x84,
	0xe5, 0x49, 0x1d, 0x5a, 0x68, 0xe4, 0x75, 0xc2, 0x8c, 0x79, 0x7d, 0x13, 0x63, 0x47, 0xb0, 0x46,
	0x03, 0x1d, 0xe4, 0x89, 0x08, 0xd1, 0x6a, 0x35, 0xac, 0x07, 0x14, 0x7f, 0x63, 0xc2, 0x24, 0xb7,
	0x0f, 0x75, 0x0f, 0xc9, 0x97, 0x6d, 0x49, 0xb7, 0x20, 0xb6, 0x0b, 0x76, 0x15, 0x90, 0x3b, 0x2b,
	0x94, 0xaf, 0x51, 0xe4, 0xad, 0xb3, 0xc5, 0xa6, 0x55, 0x88, 0x19, 0xf2, 0x55, 0x8f, 0xdf, 0x37,
	0x11, 0x8f, 0x6f, 0x8a, 0x58, 0xf3, 0xf9, 0x66, 0xff, 0x49, 0x3a, 0xc5, 0x54, 0xf2, 0xa6, 0x97,
	0xbe, 0xc0, 0x54, 0x9a, 0x6f, 0x4a, 0x8d, 0xd2, 0x5c, 0xcb, 0x94, 0x33, 0xfb, 0x4d, 0xb9, 0xa5,
	0xc9, 0x44, 0xb1, 0xca, 0xa5, 0x42, 0xde, 0xb2, 0x19, 0xb7, 0x64, 0xc7, 0xd0, 0x72, 0x8f, 0xc1,
	0x8d, 0x2c, 0x3e, 0x60, 0x61, 0xb7, 0x5e, 0x27, 0x54, 0xd3, 0xa5, 0x7e, 0xa2, 0x0c, 0x95, 0xf0,
	0x39, 0xac, 0x97, 0xf1, 0xb1, 0x4e, 0x90, 0x6f, 0x10, 0x81, 0x4d, 0x13, 0x4c, 0x86, 0x7d, 0x06,
	0xac, 0xc4, 0x30, 0xed, 0x7c, 0xec, 0x26, 0xc7, 0xc7, 0x9b, 0xa6, 0xce, 0xd6, 0x43, 0xf3, 0xb1,
	0x39, 0xa7, 0x1e, 0x9a, 0x92, 0x59, 0x75, 0x33, 0x70, 0x7c, 0x8e, 0xba, 0x19, 0xbb, 0x27, 0xb0,
	0x64, 0x0d, 0x4c, 0x86, 0xfc, 0x89, 0x35, 0x82, 0xd6, 0xaf, 0x87, 0x66, 0x9a, 0x6c, 0xaa, 0x40,
	0x75, 0x9d, 0x68, 0xbe, 0x65, 0xa7, 0x89, 0x62, 0x3d, 0x0a, 0xf9, 0x10, 0xa1, 0x64, 0xc6, 0xb7,
	0xa7, 0x20, 0x26, 0xc4, 0x5e, 0x42, 0xd3, 0x87, 0xd8, 0x46, 0xed, 0x10, 0x6e, 0xd5, 0xc3, 0x51,
	0xbb, 0x76, 0x01, 0x2e, 0x65, 0x92, 0xc8, 0x9b, 0xe0, 0x3a, 0x4f, 0xf8, 0xae, 0xed, 0xa6, 0x8d,
	0xbc, 0xcb, 0x13, 0xd6, 0x86, 0xc6, 0xc7, 0x30, 0xb8, 0x56, 0x63, 0x0b, 0xf6, 0xec, 0xb4, 0x7c,
	0x0c, 0xdf, 0x29, 0xf7, 0xee, 0x7b, 0x50, 0x1f, 0x23, 0x8c, 0xa5, 0xfb, 0x56, 0xc1, 0x02, 0x8c,
	0x97, 0x5e, 0xde, 0x98, 0xd2, 0xf6, 0xf3, 0xc6, 0x0d, 0x6f, 0x07, 0x6a, 0xfa, 0x81, 0xbf, 0x03,
	0x75, 0xbb, 0x03, 0xcb, 0x13, 0x04, 0xb5, 0xb9, 0x63, 0x5f, 0xd9, 0x41, 0xa8, 0xbf, 0x7b, 0x00,
	0x79, 0x41, 0xef, 0x16, 0x0f, 0x91, 0x1f, 0xba, 0xcf, 0x74, 0x12, 0x61, 0xaf, 0x80, 0xdd, 0xae,
	0x82, 0x54, 0x64, 0x62, 0x80, 0x05, 0x7f, 0x6a, 0x1b, 0x7a, 0x9b, 0xb9, 0xb0, 0x09, 0x03, 0x17,
	0x61, 0x18, 0x47, 0xd4, 0xa5, 0x58, 0xbc, 0x8f, 0x93, 0x58, 0x8f, 0xf8, 0x33, 0x0b, 0x1f, 0x67,
	0x5e, 0x8f, 0x13, 0xec, 0x4b, 0x78, 0x3c, 0xa3, 0x1e, 0xe4, 0x52, 0x69, 0xfe, 0x3f, 0xa2, 0xac,
	0x97, 0x77, 0x78, 0x23, 0x95, 0x66, 0xa7, 0xb0, 0x31, 0xcb, 0x32, 0x1e, 0x3e, 0x27, 0x52, 0xab,
	0x4c, 0x32, 0x6e, 0xce, 0xe5, 0x18, 0x5f, 0x8f, 0xe6, 0x73, 0x8c, 0xc3, 0x5f, 0xc1, 0xe6, 0x2c,
	0xc7, 0x3a, 0xf9, 0x82, 0x58, 0x1b, 0x65, 0xd6, 0xe4, 0x9b, 0x99, 0xfa, 0x6f, 0xd9, 0x39, 0x7a,
	0x69, 0xa7, 0xda, 0xff, 0x79, 0x99, 0x41, 0xea, 0x28, 0x58, 0xed, 0xa1, 0xf2, 0x8f, 0x92, 0xa9,
	0x73, 0xf3, 0xe1, 0x9d, 0xe7, 0xe6, 0xd7, 0xb3, 0xe7, 0xe6, 0xee, 0x5d, 0xe7, 0x66, 0xe9, 0xc4,
	0x3c, 0xfd, 0xab, 0x02, 0x8d, 0xa9, 0x2d, 0xaf, 0x60, 0xa1, 0x2f, 0x86, 0xc8, 0xee, 0x57, 0xd8,
	0xda, 0xf6, 0xd3, 0xa5, 0xb2, 0x3b, 0x4f, 0x7f, 0xff, 0xfb, 0x9f, 0x3f, 0x2a, 0x7b, 0x9d, 0x9d,
	0x93, 0xf8, 0x97, 0x2b, 0x21, 0xaf, 0xae, 0x5f, 0xb9, 0x2b, 0x87, 0xbd, 0x52, 0xd8, 0x67, 0xf6,
	0x33, 0x2c, 0xba, 0xeb, 0xc1, 0xc6, 0xb4, 0x98, 0xbb, 0x5c, 0x6c, 0x95, 0xc2, 0xee, 0x32, 0xf1,
	0x1f, 0xd5, 0x25, 0x2c, 0xd0, 0xd9, 0xbf, 0x5f, 0xd2, 0x2e, 0x5f, 0x0e, 0xee, 0x7f, 0x93, 0x17,
	0xb4, 0xd7, 0x21, 0x3b, 0xb8, 0x6f, 0xaf, 0x93, 0x5f, 0xbb, 0xe7, 0xbf, 0xbd, 0x5f, 0xa4, 0xeb,
	0xd1, 0x17, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xc2, 0xbd, 0x8c, 0x5f, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdverseEventClient is the client API for AdverseEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdverseEventClient interface {
	Save(ctx context.Context, in *AdverseEventModel, opts ...grpc.CallOption) (*ResAdverseEvent, error)
	Search(ctx context.Context, in *RepSearch, opts ...grpc.CallOption) (*ResSearch, error)
	View(ctx context.Context, in *RepAdverseEventView, opts ...grpc.CallOption) (*ResAdverseEvent, error)
}

type adverseEventClient struct {
	cc *grpc.ClientConn
}

func NewAdverseEventClient(cc *grpc.ClientConn) AdverseEventClient {
	return &adverseEventClient{cc}
}

func (c *adverseEventClient) Save(ctx context.Context, in *AdverseEventModel, opts ...grpc.CallOption) (*ResAdverseEvent, error) {
	out := new(ResAdverseEvent)
	err := c.cc.Invoke(ctx, "/datacenter.AdverseEvent/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adverseEventClient) Search(ctx context.Context, in *RepSearch, opts ...grpc.CallOption) (*ResSearch, error) {
	out := new(ResSearch)
	err := c.cc.Invoke(ctx, "/datacenter.AdverseEvent/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adverseEventClient) View(ctx context.Context, in *RepAdverseEventView, opts ...grpc.CallOption) (*ResAdverseEvent, error) {
	out := new(ResAdverseEvent)
	err := c.cc.Invoke(ctx, "/datacenter.AdverseEvent/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdverseEventServer is the server API for AdverseEvent service.
type AdverseEventServer interface {
	Save(context.Context, *AdverseEventModel) (*ResAdverseEvent, error)
	Search(context.Context, *RepSearch) (*ResSearch, error)
	View(context.Context, *RepAdverseEventView) (*ResAdverseEvent, error)
}

func RegisterAdverseEventServer(s *grpc.Server, srv AdverseEventServer) {
	s.RegisterService(&_AdverseEvent_serviceDesc, srv)
}

func _AdverseEvent_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdverseEventModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdverseEventServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datacenter.AdverseEvent/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdverseEventServer).Save(ctx, req.(*AdverseEventModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdverseEvent_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdverseEventServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datacenter.AdverseEvent/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdverseEventServer).Search(ctx, req.(*RepSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdverseEvent_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepAdverseEventView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdverseEventServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datacenter.AdverseEvent/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdverseEventServer).View(ctx, req.(*RepAdverseEventView))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdverseEvent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datacenter.AdverseEvent",
	HandlerType: (*AdverseEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _AdverseEvent_Save_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _AdverseEvent_Search_Handler,
		},
		{
			MethodName: "View",
			Handler:    _AdverseEvent_View_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adverse_event.proto",
}
